server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5551/Hotel
    username: Hotel
    password: Hotel

